### ISSUE TITLE
Paragraph-Ids without XSLT-Script

### ISSUE THREAD

**Issue by CharlotteFeidicker** [scta-texts/bcg6es#2]
I deleted some paragraphs <p/> with their Id and I created new paragraphs. 
Normally, the paragraphs get their random Id by running the id-xslt-script. 
In my case, I just copied the old Ids of the deleted paragraphs and pasted them to the new paragraphs. Also, I made random Ids up for some more paragraphs. I was aware of the fact that there must not be the same Id twice. 
So, in total, this should not be a problem, right?
Thanks.

**Comment by jeffreycwitt** [comment]
@CharlotteFeidicker that all sounds perfect. There's no problem manually creating ids. But when you do its best to follow the basic pattern "topLevelid-itemid-paraid" / ksdfjsd-sve8ns-d1de8s. If you copied the pattern of the other paragraph ids, then you're all set. Oxygen should also give you an error if you accidentally create a duplicate id.

**Comment by CharlotteFeidicker** [comment]
@jeffreycwitt ok, thanks! I copied the pattern. Everything should be fine.

**Comment by CharlotteFeidicker** [comment]
The question was answered, therefore the issue can be closed.
