### ISSUE TITLE
Several verses quoted with one reference

### ISSUE THREAD

**Issue by CharlotteFeidicker** [scta-texts/bcg6es#6]
I found a reference followed by the quotation of two verses in a direct succession. As I can not refer to both in one quotation id, I created a new `<quote/>` element. As both quotations refer to the same reference, I might get an error while adding the `<ref@target/>` or `<ref@corresp/>` Attribute. Should I create a second `<ref/>`  that wrappes around the second `<quote/>` ? Would this `<ref/>` get the same id as the first `<ref/>`? This is the use-case: 

`<ref xml:id="bcg6es-d1e110-Rd1e1196">Ecclesiasti¬ 
              <lb ed="#P" n="9"/>cus cap. 33.</ref> <quote xml:id="bcg6es-d1e110-Qd1e1199" source="http://scta.info/resource/sir33_19" synch="8-11">Rectores Ecclesiae auribus percipite.</quote> <quote xml:id="bcg6es-d1e110-Qd1e1201" source="http://scta.info/resource/sir33_20" synch="1-19">Filio &amp; Mulieri,  
          <lb ed="#P" n="10"/>Fratri &amp; Amico, non des potestatem super te in vita tua; &amp; ne 
          <lb ed="#P" n="11"/>dederis alii possessionem tuam.</quote>`

**Comment by jeffreycwitt** [comment]
I would treat this as one quote, and let the `@source` and `@synch` taken multiple values separated by white space. 

As follows:

```xml
<quote xml:id="bcg6es-d1e110-Qd1e1199" 
             source="http://scta.info/resource/sir33_19 http://scta.info/resource/sir33_20" 
             synch="8-11 1-19">
     Rectores Ecclesiae auribus percipite. Filio &amp; Mulieri, Fratri &amp; Amico, non des potestatem super te in vita tua; 
    &amp; ne dederis alii possessionem tuam.
</quote>
```

I know it gets a little messy, but it will work. The source id and the synch values will align as long as you list the same order.

**Comment by CharlotteFeidicker** [comment]
Okay, thanks! I did not know that this was possible but it seems like a good solution to me.
