### ISSUE TITLE
Head - element

### ISSUE THREAD

**Issue by CharlotteFeidicker** [scta-texts/bcg6es#7]
In the file of distinctio 5, the `<head>Distinctio 5</head>` may be changed to the title given in the 1632 text. I inserted the original title. This title is very long and written in several lines. Should the `<head/>` element therefore contain `<lb/>` ? If yes, how should these lines be counted?

**Comment by jeffreycwitt** [comment]
In this case leave the `<head>Distinction 5<head>` as is. This is meant to be "metadata" for the parent `<div>` not necessarily to represent what is in this particular witness. 

To represent the heading in the text, I still use a `<p ana="#heading">` which can then take `<lb>` like any other paragraph. 

So something like: 

```xml
<div>
<head>Distinctio 5</head>
<p ana="#heading">
   <lb n="1"/>quinta distinctio
</p>
<p>
   <lb n="2">More text
</p>
```

It's definitely not an obvious solution. But headings are very tricky, as we want to use the both for catalogue metadata and also as text that can be read and compared like any other part of the text. These two functions can come into conflict. Separating `<head>` from `<p ana="#heading">` is the "in-progress" solution I'm currently exprimenting with.

**Comment by CharlotteFeidicker** [comment]
Seems like a good solution to me, thanks.

**Comment by CharlotteFeidicker** [comment]
Seems to be fine.
