### ISSUE TITLE
Highlighted letter at the beginning of dist 5

### ISSUE THREAD

**Issue by CharlotteFeidicker** [scta-texts/bcg6es#8]
Hallo @jeffreycwitt , 
I inserted the first letter of the fifth distinctio "Q". It was not transcribed by Transkribus because of it is bigger than normal letters and has some embellishment. I couldn't find any information on such letters in the LombardPress-Guidelines so I searched for a solution in the Epidoc-Guidelines and decided to go with `<hi rend="tall">Q</hi>`.

**Comment by jeffreycwitt** [comment]
That's fine.

At present, it won't be rendered in any presentations I have created; but it won't cause any problems.
